language: "perl"

perl:
  - "5.10"

env:
  - COVERALLS=false

sudo: required
services:
  - docker


before_install:
    - docker pull robsyme/docker-sge
    - git clone --depth 1 https://github.com/Ensembl/ensembl-hive
    - perl -version
    - env

install:
    - cpanm -v --installdeps --notest --cpanfile ensembl-hive/cpanfile .
    - cpanm -v --installdeps --notest .

script:
    - docker run -v /home/travis:/home/travis robsyme/docker-sge /home/travis/build/muffato/ensembl-hive-sge/scripts/travis_run_tests.sh

