language: "perl"

perl:
  - "5.10"

sudo: required
services:
  - docker

install:
    - docker pull robsyme/docker-sge
    - git clone --depth 1 --branch version/2.4 https://github.com/Ensembl/ensembl-hive
    - env

script:
    - docker run -v /home/travis:/home/travis robsyme/docker-sge /home/travis/build/muffato/ensembl-hive-sge/travisci/setup_docker_and_run_tests.sh

