language: "perl"

perl:
  - "5.10"

env:
  - COVERALLS=false

sudo: required
services:
  - docker


before_install:
    - docker pull robsyme/docker-sge
    - git clone --depth 1 https://github.com/Ensembl/ensembl-hive
    - perl -version
    - env

install:
    - export PERL5LIB=$PWD/ensembl-hive/modules:$PWD/modules
    - export EHIVE_TEST_PIPELINE_URLS='mysql://travis@127.0.0.1/'
    - docker run -d -i robsyme/docker-sge
    - cd ensembl-hive
    - cpanm -v --installdeps --notest .

script:
    - prove -rv t

