services:
  - docker

install:
    - docker pull robsyme/docker-sge
    - git clone --depth 1 --branch version/2.4 https://github.com/Ensembl/ensembl-hive
    - env

script:
    - docker run -v /home/travis:/home/travis robsyme/docker-sge /home/travis/build/Ensembl/ensembl-hive-sge/travisci/setup_docker_and_run_tests.sh

notifications:
  slack:
    rooms:
      # coregithub
      - secure: Cv8zPsf3Fl15jWm50xxV+1E/bjpfkn8H6c43YKbVRBZo8t3eZMQEanMeLB31qORoZQdXXm4O4KG2U8sGBDZi187I6aL98+NemAGRyEXAIK0o5h3CH3RMHWe22c01q7p1OtzSrFqSafOWRrcTR9cGDMfriDQUGn0Wondla0UZ7d5RCUorZ8r3KcXfGYccAMfKNfrYTtfy9qyTnvqJLsB4z2o+ok6Y+6WCmWepADnyNR5RMwiuteGtYJze+L/sCN9ijaJqr9EGaghDl61H65R5lGh/nc5pCg1sikI7BPXipe1jraUIZAQrkMyL8ttC+z38BF9qaKb8r+CkzbPsIeey18VNa3G6XcPER2NtXoq86HDXk2WvkoeLIhax5EuexNNVoHQcD38TX5xxolHZk+Jtom+DsP2RDzlTKAQUdkfjOgGUJHq9i29ZvrNSeRZvRQyGR6giU/9iCmqmV7q/VjAwbpFfBLnlFVt3QRo/Ztk+Ljp4I2UpK7GlcBBLLfafq2hLzYy2cXJWJ2LH3bW0xNvaVCP+2ko3OPw0tdvxP0xSbqhDU2U1pL5t+vaxmRNrUMRO2nl6DA+ZU0VTU06tXczwJaDSea0XCAkJ78BTpB8fbtCJitCxPENkiyi9kEQb9MBe8v+GEvJ75lV1VYp/Qn2iuSnpoCipMlayQKU8Y7JWAA4=
      # ehive-commits
      - secure: cEbVfqkEUzTs4wK0JgAZJoHDn5ZGW9mkLlOzq4ayoIWIfDDcKrBMpd7Sz6MIu5sVTKG15GEiQnGCzFr0D592sH7gCTblIqXymuIP8OFIJx8rJWxHHfSIYrW/M1kOJ0w4napgSLb3W+Dz4jsnnPcdymwbFVc6iD97RY162H4MOxUnLR5nRs+Dvk544aafJTbltpBvcdtqJ3e5+q6XQRQohFKuLNXhsWLqtQcdpH2+C93epmpqFf8Jx0EQLbG1nBS+EGwrO3tLko7XV2q7Dc+75M8TYajLHZ/DfZs2tqRnvggKvzoQyWkwvHJJItknZ+vAYYqQJrJ1yV+XWDWuZ8A1UThY6LcJSMdVCp5cg0AzARWmT8FQsCkq5VsN2X8wuKyFveZBNwwjenUB1B0a6XqaxBZRkgXz4i0ecKMMPQvKNN9Y+Fa3P2DbP3X2unXr1HDRaD2au8Cf0RRqRdco+JZGoI8rAkjJtxY3GLRfeSgIcUMo0O90sXxdL3cayvKmX2V6BfT527vDTcZ3j2sxs25PBoTY1CVC2tm0DsuPh4agN4e5bD3LDVGgFg8Uefu6PMS9Rqkba3afyNFue8Q3H5mPeHv19kV8Ta4ikciO8wcfjqKwnlfhAGuf7wKBNa15MFT1g7T48oVmAYyIkweb7ENpEmgVTDCwRJIiuqefvXHAqqo=
    on_failure: change
